### ISSUE TITLE
Switch to strict floating point math?

### ISSUE THREAD

**Issue by RyanTaker** [jbox2d/jbox2d#19]
Lately, I have been concerned about the cross-platform capabilities of my program and thus added the strictfp tag to all float-calculating functions (except for rendering) and switched from using Math to StrictMath. This is not triggered by default as it made a fairly large difference on old systems, but now, my testing shows < 1% difference. It is difficult to allow the user to choose without using some Reflection madness.

**Comment by mucaho** [comment]
The [remaining non-determinism](http://stackoverflow.com/a/17626306/3041008) could be because of:
* `Object.hashCode()`: Try implementing `equals` and `hashCode` for all classes, or at least for the ones that are used in `HashMap`s and `HashSet`s
* `Random`s should be initialized with the same seed across multiple runs.

**Comment by mucaho** [comment]
I wrote a small test that executes 1000 steps of the [`Domino Tower`](https://github.com/jbox2d/jbox2d/blob/master/jbox2d-testbed/src/main/java/org/jbox2d/testbed/tests/DominoTower.java) test and constructs a checksum over all body positions, angular- & linear-velocities.
I am still waiting for response from some of my friends I sent it too, but preliminary testing on different architectures, OSes and java versions looks promising.

@RyanTaker could you share your tests that show different results, please? I can't see a difference in the checksums from my preliminary tests.

[Here is the gist](https://gist.github.com/mucaho/fcbd9bfd1ce3111d518b) of the test. Make sure you build jbox2d with #20 .
The executable jar file (`java -jar jbox2d-checksum.jar`) is here. Be sure to rename the file extension from `png` to `jar`. ![jbox2d-checksum.png](https://cloud.githubusercontent.com/assets/3935691/7554831/fd713b2c-f737-11e4-9923-a8479f704016.png)

**Comment by mucaho** [comment]
@dmurph 
From a recent discussion on JavaGaming forum, there is the possibility of adding `strictfp` modifiers just before the class is loaded by the classloader. This should incur no performance overhead after "warm-starting" the game and avoids the issue of having seperate codebases for a strict and non-strict variant of JBox2D. [here is the link](http://www.java-gaming.org/topics/jbox2d-networking-reproducibility-and-determinism/36266/msg/343653/view.html#msg343653)
