### ISSUE TITLE
I don't want to set up maven, where are the jars?

### ISSUE THREAD

**Issue by biophonism** [jbox2d/jbox2d#38]
I don't want to set up maven, where are the jars?

**Comment by alyphen** [comment]
**Library:**
http://search.maven.org/remotecontent?filepath=org/jbox2d/jbox2d-library/2.2.1.1/jbox2d-library-2.2.1.1.jar

**Serialization:**
http://search.maven.org/remotecontent?filepath=org/jbox2d/jbox2d-serialization/1.1.0/jbox2d-serialization-1.1.0.jar

**Testbed:**
http://search.maven.org/#artifactdetails%7Corg.jbox2d%7Cjbox2d-testbed%7C2.2.1.1%7Cjar

**Testbed (JOGL):**
http://search.maven.org/remotecontent?filepath=org/jbox2d/jbox2d-testbed-jogl/1.0.1/jbox2d-testbed-jogl-1.0.1.jar

**Comment by dmurph** [comment]
Those are the old jars with bad performance unfortunately. I couldnt get
mvn release to work again for 2.3.0. I'll bundle the jars in a bit

**Comment by RoyRGitHub** [comment]
> Those are the old jars with bad performance unfortunately. I couldnt get
> mvn release to work again for 2.3.0. I'll bundle the jars in a bit
> 
> On Thu, Jun 18, 2015, 7:59 AM AndresQ [notifications@github.com](mailto:notifications@github.com) wrote:
> 
> > Closed #38 #38.
> > —
> > Reply to this email directly or view it on GitHub
> > [#38 (comment)](https://github.com/jbox2d/jbox2d/issues/38#event-334292578).

Is there any progress with the 2.3.0 non maven version ? thanks !

**Comment by Ahartry** [comment]
Can we have an updated on new versions of the .jar files?

**Comment by dmurph** [comment]
I hope that I put them in here: https://github.com/jbox2d/jbox2d/releases/tag/jbox2d-2.3.0-BETA

**Comment by Ahartry** [comment]
That doesn't seem to have any .jar files, so I compiled my own. I haven't tested it at all yet, but here is the most recent github version, compiled for jdk 22:
https://drive.google.com/file/d/128ajymsyu_BDm9QPBJzTMB8kyuc2NArM/view?usp=sharing
