### ISSUE TITLE
JavaFX support

### ISSUE THREAD

**Issue by hallvard** [jbox2d/jbox2d#43]
I want to use JBox2D in a JavaFX environment, and my initial experiments are successful. As part of understanding various issues, I looked at the testbed, but I couldn't find a JavaFX port. I ended up doing it myself, so now I both have a testbed running and a better understanding of JBox2D. The question is, how should it be packaged/contributed? I had to make some changes to the testbed.framework package, as well as the j2d version, to make the javafx version cleaner. Currently it's in the same project, should it be a separate one like the one for jogl, like jbox2d-testbed-javafx?

**Comment by mhvelplund** [comment]
Maybe close this if the code if #44 has been merged?

**Comment by dmurph** [comment]
Ah yeah, thanks :)
