### ISSUE TITLE
Spelling Mistake in Sweep class

### ISSUE THREAD

**Issue by Anarki01** [jbox2d/jbox2d#47]
There is a spelling mistake on line 30.
"the body origin, which may no coincide with the center of mass. However, to support dynamics we"
should be changed to:
"the body origin, which may not coincide with the center of mass. However, to support dynamics we"

![sweep spelling mistake](https://cloud.githubusercontent.com/assets/17553446/20355349/c17fff24-ac29-11e6-9e28-f0b20ead8b1d.jpg)

**Comment by Anarki01** [comment]
For convenience, the spelling mistake is in the follwing file path:
jbox2d-master\jbox2d-library\src\main\java\org\jbox2d\common\Sweep.java

**Comment by tulsidas** [comment]
fixed, thanks!
