### ISSUE TITLE
Serialization BUG

### ISSUE THREAD

**Issue by SSSxCCC** [jbox2d/jbox2d#48]
I am running a world which uses body.applyForce() to push bodies, I deserialize my world, then something really strange happened -- the bodies are forced faster several times than before. I didn't find where is wrong. So I run the Apply Force Test in JBox2D Testbed to just click button 'Save' and 'Load'. Then same strange thing happened, When I pressed the key 'w', 'a', 's', 'd', the body controlled by me moved faster several times than before, it is too fast to be manipulated.
My jre/jdk is 1.8.0_112 and I have tried jbox2d-2.1.2.3, 2.2.1.1 and master. Have you met anything like this? Where on earth is wrong?

**Comment by dmurph** [comment]
it sounds like there is a bug in the testbed code
