### ISSUE TITLE
ParticleType.b2_colorMixingParticle 

### ISSUE THREAD

**Issue by diwi** [jbox2d/jbox2d#53]
Incorrect results when Particles are flagged as b2_colorMixingParticle:

Error: bytewise color-difference
https://github.com/jbox2d/jbox2d/blob/master/jbox2d-library/src/main/java/org/jbox2d/particle/ParticleSystem.java#L1178

Fix: & 0xFF before subtraction
```
        int dr = (colorMixing256 * ((colorB.r & 0xFF) - (colorA.r & 0xFF))) >> 8;
        int dg = (colorMixing256 * ((colorB.g & 0xFF) - (colorA.g & 0xFF))) >> 8;
        int db = (colorMixing256 * ((colorB.b & 0xFF) - (colorA.b & 0xFF))) >> 8;
        int da = (colorMixing256 * ((colorB.a & 0xFF) - (colorA.a & 0xFF))) >> 8;
```

**Comment by deecewan** [comment]
would be very cool if this patch could be included.

**Comment by tulsidas** [comment]
@deecewan can you create a pull request from https://github.com/ferocia/jbox2d/commit/fee41f700ed5be929897ff408a23ee8cadae6583?
